### ISSUE TITLE
Selecting text area opens keyboard after refocusing the app

### ISSUE THREAD

**Issue by MKrabs** [Darkempire78/OpenCalc#71] opened 2022-11-07 16:40 UTC
Re-opening the app, after selecting/focusing the text area opens the keyboard (and squishes the entire layout)

https://user-images.githubusercontent.com/71791731/200363661-125c4bea-e9a0-4867-a896-678b642f8688.mp4

Phone: Samsung S22
OS: Android 13 - OneUI 5.0

**Comment by Darkempire78** [comment] 2022-11-07 17:48
That's very weird because I'm not able to reproduce that on my Google pixel 6 (Android 13)

**Comment by Darkempire78** [comment] 2022-11-11 01:25
Ara you using the latest version of OpenCalc ?

**Comment by Paol-M** [comment] 2022-11-17 11:37
> Ara you using the latest version of OpenCalc ?

[not OP] I had the same bug on Samsung. Updating to latest version fixed it

**Comment by Darkempire78** [comment] 2022-11-18 17:49
@MKrabs Is it fixed ?

**Comment by Darkempire78** [comment] 2022-11-20 12:54
I'm closing the issue because it needs to be fixed, if not reopen it with more information

**Closed by Darkempire78** 2022-11-20 12:54 UTC
Labels: bug, cannot reproduce
