### ISSUE TITLE
Creating or deleting a thousand separator causes the cursor to jump.

### ISSUE THREAD

**Issue by Markus40** [Darkempire78/OpenCalc#218] opened 2023-03-05 05:47 UTC
**Describe the bug**
Creating or deleting a thousand separator causes the cursor to jump.

**To Reproduce**
- For users with "." as the decimal separator reverse the use of "." and ","
- Input: 1,23456
- Put a + between the numbers 2 and 3
- Cursor jumps between numbers 3 and .4

**Expected behavior**
Cursor should stay after + and in front of number 3

**Smartphone:**
 - Device: [Samsung Galaxy A52 5g]
 - OS: [Android 13]
 - Version [2.1.3]
 - Language [German]

**Comment by mwadle** [comment] 2023-10-28 00:21
This seems to be caused by the way update display calculates cursor position. It seems to work fine when a number is inserted, but the shift that comes from entering a symbol can cause issues. This can be fixed by setting the cursor to the position of leftString.length + value.length when a symbol (any non-number) is inserted.

The only issue I see is this formatting method can be broken when inserting values from history, which would include numbers and symbols. The easiest way around this that I can think of is to just wrap anything inserted from history in parenthesis (if it isn't already). That way we can just treat anything that isn't a single number (including entries from history) as a symbol and be done with it.

I believe wrapping things we insert from history in parenthesis makes sense anyways, because you would want to insert the previous calculation as a single unit and you can remove the parenthesis later if needed. Still, this is the kind of change that I think @Darkempire78 might have an opinion on.

**Comment by Darkempire78** [comment] 2023-10-28 07:11
@mwadle I think that you are right, it seems to be the best solution. Can you open a pull request for that ?

**Comment by mwadle** [comment] 2023-10-28 17:12
Yes. I'll aim to have it submitted by the end of the weekend.

**Comment by Darkempire78** [comment] 2023-11-01 11:32
Fixed

**Closed by Darkempire78** 2023-11-01 11:32 UTC
Labels: bug, help wanted, important
