### ISSUE TITLE
Decimals cause value errors

### ISSUE THREAD

**Issue by is-code-afish** [Darkempire78/OpenCalc#114] opened 2022-12-01 16:12 UTC
In latest version, adding a decimal to a number will add an unexpected and incorrect "0" to every value left of the decimal.

**Comment by Darkempire78** [comment] 2022-12-01 16:32
Try using the v2.0.0-beta3 it must be fixed

**Comment by is-code-afish** [comment] 2022-12-01 16:41
> 

I can re check, but I believe I'm on the latest version on f-droid, or what it claims as such.

**Comment by Darkempire78** [comment] 2022-12-01 16:59
The issue is fixed for me, are you sure ?

**Comment by is-code-afish** [comment] 2022-12-01 17:57
![Screenshot_20221201-115438_Calculator](https://user-images.githubusercontent.com/111070707/205125678-5f3fc831-cc1e-493b-942a-8cc3e918e02f.jpg) this qol feature.
![Screenshot_20221201-115458_Calculator](https://user-images.githubusercontent.com/111070707/205125788-7f567fff-e6a3-4f58-86ee-3579b680995c.jpg)
It works properly when there is only 1 previous digit
![Screenshot_20221201-115500_Calculator](https://user-images.githubusercontent.com/111070707/205125951-a00028fa-5b84-4ee1-8131-80bb218e023c.jpg)

**Comment by Darkempire78** [comment] 2022-12-01 20:30
I'm not able to reproduce it ( I tried in French and English)

**Comment by eXense-auth** [comment] 2022-12-02 07:03
> 

try russian please

**Comment by Stalthdan** [comment] 2022-12-03 07:06
I've encountered this issue too, I'm on version 2.0.0-beta2.

Try entering 4004.25
It'll show up as 40,040.25
Then when erasing up to the decimal, is changes to 400,400

My system language is English (United Kingdom), running Android 9.

**Comment by Darkempire78** [comment] 2022-12-03 12:02
@eXense-auth @Stalthdan This version should be fixed in the v2.0.0-beta3, can you confirm me taht it was fixed ? I'm not able to reproduce it since the beta3

**Comment by Stalthdan** [comment] 2022-12-03 12:14
@Darkempire78 Yes, it seems to have been fixed in v2.0.0-beta3.

**Closed** 2022-12-03 23:53 UTC
