### ISSUE TITLE
Crashes on input of <a number>%

### ISSUE THREAD

**Issue by CalAlaera** [Darkempire78/OpenCalc#168] opened 2023-02-17 23:47 UTC
**Describe the bug**
The app crashes when <a number>% is input.

**To Reproduce**
1. Open the app or press AC
2. Input e.g. 100% or 0% or 5.4%
3. App crashes

**Expected behavior**
The app does not crash and either divides the input by 100 or displays Math Error.

**Screenshots/videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Samsung Note9
 - OS: Android 10
 - Version 2.0.0 (latest F-Droid version)
 - Language English

**Comment by Darkempire78** [comment] 2023-02-17 23:49
What is your version of OpenCalc ?

**Comment by CalAlaera** [comment] 2023-02-17 23:50
Applies to v2.0.0, current F-Droid build. I unfortunately can't test more recent versions.

**Comment by CalAlaera** [comment] 2023-02-17 23:56
2.0.0

Updated my initial comment with the template format as requested

**Comment by Domefemia** [comment] 2023-02-18 08:45
That's the crash O wanted to report lmao. Anyway the app crash if you put a positive number and the % sign. (For negative numbers work as intended)
But if the positive number is obtained as result of an operation the crash doesn't happen, for example if you do 5 and the % it does crash but if you do (5) and the % it works correctly!

**Comment by Darkempire78** [comment] 2023-02-18 13:43
So, can you all tell me if the bug is fixed in the v2.1.0 ?

**Comment by Darkempire78** [comment] 2023-02-18 14:04
Update: The big is well present in the v2.0.0, but is patched in the v2.1.0, thanks for the report

**Closed by Darkempire78** 2023-02-18 14:04 UTC
Labels: bug, cannot reproduce
