### ISSUE TITLE
[BETA-BUG] Selected theme is wrong and weird

### ISSUE THREAD

**Issue by inson1** [Darkempire78/OpenCalc#326] opened 2023-10-24 10:19 UTC
**Screenshots/videos**

What is? "THEME" (It happened when I first opened the app)
![IMG_20231024_120231.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/e63f2bc1-ed79-4100-bd06-72f2d9497477)

Selected theme was Dark theme 
![Screenshot_2023-10-24-12-05-38-729_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/bf255dc9-e5c3-4f2a-b271-2637734b9920)

Selected theme was System theme (System theme was Dark theme)
![Screenshot_2023-10-24-12-05-20-493_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/061f0548-3c37-4b3b-9795-e74b3846bba8)

Selected theme was Light theme
![Screenshot_2023-10-24-12-15-09-368_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/144322fd-bf8b-4944-a1a2-1b5b5320484d)

![Screenshot_2023-10-24-12-15-14-874_com.darkempire78.opencalculator.jpg](https://github.com/Darkempire78/OpenCalc/assets/75314629/7f9b032e-51d7-44ad-b862-5f3e74af166d)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi note 8 Pro
 - OS: Android 11 MIUI 12.5.7
 - Version: 3.0.0 beta 2
 - Language:  English

**Comment by Darkempire78** [comment] 2023-11-01 12:00
the "THEME" should be fixed, but I'm not able to reproduce your other bugs with themes

**Comment by Darkempire78** [comment] 2023-11-01 12:07
This commit 55ffda38471d78b33920cf7e0b842deaf77e06c3 fix the default THEME value, open a new issue for your other theme issue please. One channel per issue

**Closed by Darkempire78** 2023-11-01 12:07 UTC
Labels: bug, cannot reproduce

**Comment by inson1** [comment] 2023-11-03 11:36
@Darkempire78 It was all connected, If first value was right then maybe all values would be right

I will wait for next release of the beta and try it

**Comment by inson1** [comment] 2023-11-05 21:48
@Darkempire78 
THEME is solved, 
second problem that I thought could be related, is solved partly - System shows Light, but set is Dark theme (default in system), others themes seems working - I creatw another issue for that

**Comment by inson1** [comment] 2023-12-18 10:15
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
