### ISSUE TITLE
letter support

### ISSUE THREAD

**Issue by Wjxfi** [Darkempire78/OpenCalc#223] opened 2023-03-07 12:45 UTC
examples:

e=mc^2

x^2y+x+xy^2+y+2xy+2

x^2 + 6x + 5

(x - 3)(x + 7) - 13 = (x + 8)(x - 4) - 2

(x + 1)(x + 2)(x + 3)

Letters are important.

I would like to be able to use them.

solution suggestion:

long press on ! to show the 10 most popular letters (for math) in place of all digits. 
long press on % to show 10 other letters (except for those shown on !) in place of all digits. 
long press π to display 6 other letters (except those shown at ! and %) instead of almost all numbers. 

To close the alphabet you will need to do the following:
https://user-images.githubusercontent.com/113500363/223429495-be844d81-0edf-4e56-bc14-ca4c099b9dd2.mp4
(once)

so we could fit the entire English alphabet into one calculator. I really hope this will be added

**Comment by Darkempire78** [comment] 2023-03-07 12:58
I can understand constants like g=9.81, but what is the use of x or y here ? We cannot define a variable

**Comment by Darkempire78** [comment] 2023-03-19 15:38
This is not planned for the moment because it will make the calculator too complex

**Comment by ctntt** [comment] 2023-03-21 00:08
> Right now the calculator is incomplete. but when it is done it will be much better and there will be no changes in the interface since it will be hidden. 

I wouldn't say it is incomplete. A simple calculator app doesn't need to support every feature. Mathematics is a huge topic and many features could be added which wouldn't make the app better for most users.

The fact that the feature should be hidden would mean most users wouldn't notice its existence and wouldn't benefit from it. If this feature would be included, the app would definitely need a small UI change like a extra button for letters.

Also polynomial factorization, primality proof, etc. isn't that easy. I am not an app developer but I guess that this feature would take too much time and therefore the decision to close the issue is justified. 

At the same time there already are good open source tools for your purposes. For example check out SymPy.

**Closed** 2023-04-15 18:05 UTC
Labels: enhancement, wontfix

**Comment by ctntt** [comment] 2023-04-15 22:18
Darkempire already explained it.
> This is not planned for the moment because it will make the calculator too complex

I am almost certain that this feature wont make it into OpenCalc even if the issue stays open. Maybe one day someone who *really* wants this feature forks the project and develops it themself.
